services:
  hh_applicant_tool:
    container_name: hh_applicant_tool
    image: hh_applicant_tool:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    environment:
      CONFIG_DIR: /app/config
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Europe/Moscow}
      HH_AUTOMATION_MODE: ${HH_AUTOMATION_MODE:-off}
      HH_PROFILE_PARALLELISM: ${HH_PROFILE_PARALLELISM:-10}
