services:
  hh_applicant_tool:
    container_name: hh_applicant_tool
    image: hh_applicant_tool:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    environment:
      CONFIG_DIR: /app/config
      TERM: "${TERM:-xterm}"
      TZ: "${TZ:-Europe/Moscow}"
      HH_AUTOMATION_MODE: "${HH_AUTOMATION_MODE:-off}"
      HH_NAME: "${HH_NAME:-}"
      HH_TELEGRAM: "${HH_TELEGRAM:-}"
      SEARCH_QUERY: "${SEARCH_QUERY:-Frontend разработчик}"
      APPLY_LIMIT: "${APPLY_LIMIT:-100}"
      APPLY_PER_PAGE: "${APPLY_PER_PAGE:-50}"
      APPLY_PAGES: "${APPLY_PAGES:-20}"
      APPLY_RUN_TIMEOUT: "${APPLY_RUN_TIMEOUT:-3600}"
      REPLY_CHATS: "${REPLY_CHATS:-100}"
      HH_PROFILE_PARALLELISM: "${HH_PROFILE_PARALLELISM:-10}"
